version: "3.7"
networks:
  debug:
    driver: bridge
    name: debug
services:
  proxy:
    image: nginx:1.13
    volumes:
      - ./config/proxy:/etc/nginx/conf.d
    ports:
      - "443:443"
  mocklogin:
    image: lblod/mock-login-service:0.3.1
  frontend:
    restart: "no"
    ports:
      - "80:80"
  identifier:
    ports:
      - "90:80"
    restart: "no"
  dispatcher:
    restart: "no"
    networks:
      - default
      - debug
  database:
    restart: always
    networks:
      - default
      - debug
  virtuoso:
    ports:
      - "8890:8890"
    restart: "no"
  deltanotifier:
    restart: "no"
    networks:
      - default
      - debug
  migrations:
    restart: "no"
  cache:
    restart: "no"
  resource:
    restart: "no"
  login:
    restart: "no"
  sink:
    restart: "no"