version: "3.7"
networks:
  debug:
    driver: bridge
    name: debug
services:
  proxy:
    image: nginx:1.13
    volumes:
      - ./config/proxy:/etc/nginx/conf.d
    ports:
      - "443:443"
  mocklogin:
    image: lblod/mock-login-service:0.3.1
  frontend:
    restart: "no"
    ports:
      - "80:80"
    environment:
      EMBER_FEATURE_PUBLIC_SERVICES_ENABLED: "true"
      EMBER_FEATURE_EREDIENSTEN_MANDATENBEHEER_ENABLED: "true"
      EMBER_FEATURE_WORSHIP_MINISTER_MANAGEMENT_ENABLED: "true"
      EMBER_WORSHIP_DECISIONS_DATABASE_URL: "https://dev.databankerediensten.lokaalbestuur.lblod.info"
      EMBER_WORSHIP_ORGANISATIONS_DATABASE_URL: "https://dev.organisaties.lokaalbestuur.lblod.info"
  identifier:
    ports:
      - "90:80"
    restart: "no"
  dispatcher:
    restart: "no"
    networks:
      - default
      - debug
  database:
    image: semtech/sparql-parser:latest
    volumes:
      - ./config/cl-authorization:/config
    restart: always
    networks:
      - default
      - debug
  virtuoso:
    ports:
      - "8890:8890"
    restart: "no"
  deltanotifier:
    restart: "no"
  migrations:
    restart: "no"
  cache:
    restart: "no"
  resource:
    restart: "no"
  login:
    restart: "no"
  file:
    restart: "no"
  filehost:
    restart: "no"
  sink:
    restart: "no"
  person-uri-for-social-security-number:
    restart: "no"
  form-content:
    restart: "no"
    profiles:
      - nodebug
  mandataris:
    restart: "no"
    profiles:
      - nodebug
  adressenregister:
    restart: "no"
  ldes-delta-pusher:
    restart: "no"
    environment:
      DEBUG: "true"
  ldes-backend:
    restart: "no"
    environment:
      BASE_URL: "http://localhost/streams/ldes"
    ports:
      - "6666:80"
  vendor-login:
    restart: "no"
  sparql-authorization-wrapper:
    restart: "no"
  besluiten-consumer-0:
    environment:
     # #### START: 'normal operation mode' in optimal performance for direct virtuoso (needs full-reindex though)
      #SLEEP_BETWEEN_BATCHES: 1 # also maybe increast this during intial sync
      #BATCH_SIZE: 1000
      #BYPASS_MU_AUTH_FOR_EXPENSIVE_QUERIES: 'true'
      #PARALLEL_CALLS: "4" # we might be jinxing virtuoso; but let's try
      # #### END: 'normal operation mode' in optimal performance for direct virtuoso

      # #### START: 'normal operation mode' in optimal performance for mu-auth
      BATCH_SIZE: "1"
      SLEEP_BETWEEN_BATCHES: "1"
      PARALLEL_CALLS: "8"
      # #### END: 'normal operation mode' in optimal performance for mu-auth

      DCR_SYNC_BASE_URL: "https://lokaalbeslist-harvester-0.s.redhost.be/"
      DCR_DISABLE_DELTA_INGEST: "false" # uncomment to enable data ingestion
      DCR_DISABLE_INITIAL_SYNC: "false" # uncomment to enable initial sync
