version: "3.7"
networks:
  debug:
    driver: bridge
    name: debug
services:
  proxy:
    image: nginx:1.13
    volumes:
      - ./config/proxy:/etc/nginx/conf.d
    ports:
      - "443:443"
  mocklogin:
    image: lblod/mock-login-service:0.3.1
  frontend:
    restart: "no"
    ports:
      - "80:80"
    environment:
      EMBER_FEATURE_PUBLIC_SERVICES_ENABLED: "true"
      EMBER_FEATURE_EREDIENSTEN_MANDATENBEHEER_ENABLED: "true"
      EMBER_FEATURE_WORSHIP_MINISTER_MANAGEMENT_ENABLED: "true"
      EMBER_WORSHIP_DECISIONS_DATABASE_URL: "https://dev.databankerediensten.lokaalbestuur.lblod.info"
      EMBER_WORSHIP_ORGANISATIONS_DATABASE_URL: "https://dev.organisaties.lokaalbestuur.lblod.info"
  identifier:
    ports:
      - "90:80"
    restart: "no"
  dispatcher:
    restart: "no"
    networks:
      - default
      - debug
  database:
    image: semtech/sparql-parser:latest
    volumes:
      - ./config/cl-authorization:/config
    restart: always
    networks:
      - default
      - debug
  virtuoso:
    ports:
      - "8890:8890"
    restart: "no"
  deltanotifier:
    restart: "no"
    networks:
      - default
      - debug
  migrations:
    restart: "no"
  cache:
    restart: "no"
  resource:
    restart: "no"
  login:
    restart: "no"
  file:
    restart: "no"
  filehost:
    restart: "no"
  sink:
    restart: "no"
  person-uri-for-social-security-number:
    restart: "no"
  form-content:
    restart: "no"
    profiles:
      - nodebug
  mandataris:
    restart: "no"
    profiles:
      - nodebug
  modified:
    restart: "no"
    profiles:
      - nodebug
  adressenregister:
    restart: "no"
  ldes-delta-pusher:
    restart: "no"
    environment:
      DEBUG: "true"
  ldes-backend:
    restart: "no"
    environment:
      BASE_URL: "http://localhost/streams/ldes/"
    ports:
      - "6666:80"
  vendor-login:
    restart: "no"
  sparql-authorization-wrapper:
    restart: "no"
  authorization-wrapper:
    restart: "no"
  ##############################################################################
  # Besluiten consumers
  ##############################################################################
  besluiten-consumer-0:
    profiles:
      - withConsumer
    environment:
      DCR_SYNC_BASE_URL: "https://lokaalbeslist-harvester-0.s.redhost.be/"
      DCR_DISABLE_INITIAL_SYNC: "false"
      DCR_START_FROM_DELTA_TIMESTAMP: "2024-01-12T15:51:23.478Z"
  besluiten-consumer-1:
    profiles:
      - withConsumer
    environment:
      DCR_SYNC_BASE_URL: "https://lokaalbeslist-harvester-1.s.redhost.be/"
      DCR_DISABLE_INITIAL_SYNC: "false"
      DCR_START_FROM_DELTA_TIMESTAMP: "2024-01-12T15:51:23.478Z"
  besluiten-consumer-2:
    profiles:
      - withConsumer
    environment:
      DCR_SYNC_BASE_URL: "https://lokaalbeslist-harvester-2.s.redhost.be/"
      DCR_DISABLE_INITIAL_SYNC: "false"
      DCR_START_FROM_DELTA_TIMESTAMP: "2024-01-12T15:51:23.478Z"
  besluiten-consumer-3:
    profiles:
      - withConsumer
    environment:
      DCR_SYNC_BASE_URL: "https://lokaalbeslist-harvester-3.s.redhost.be/"
      DCR_DISABLE_INITIAL_SYNC: "false"
      DCR_START_FROM_DELTA_TIMESTAMP: "2024-01-12T15:51:23.478Z"
