(define-resource dossier ()
  :class (s-prefix "dossier:Dossier")
  :properties `((:name :string ,(s-prefix "dct:title")))
  :has-one `((zaak :via ,(s-prefix "dossier:Dossier.isNeerslagVan")
                   :as "is-neerslag-van")
             (aanvraag :via ,(s-prefix "omgeving:zaakhandeling")
                       :as "aanvraag"))
  :resource-base (s-url "http://data.lblod.info/id/dossiers/")
  :on-path "dossiers")

(define-resource zaak ()
  :class (s-prefix "dossier:Zaak")
  :properties `((:name :string ,(s-prefix "dct:title"))
                (:opening-date :datetime ,(s-prefix "dossier:openingsdatum"))
                (:closing-date :datetime ,(s-prefix "dossier:sluitingsdatum")))
  ;; TODO: add status
  ;; TODO: link to municipality and organizer (via project)
  ;; :has-one `((bestuurseenheid :via ,(s-prefix "ext:organizedBy"))
  ;;                             :as "organizedBy")
  :has-one `((dossier :via ,(s-prefix "dossier:Dossier.isNeerslagVan")
                      :inverse t
                      :as "dossier")
              (procedurestap :via ,(s-prefix "dossier:doorloopt")
                             :as "procedurestap"))
  :resource-base (s-url "http://data.lblod.info/id/zaken/")
  :on-path "zaaks")

(define-resource procedurestap ()
  :class (s-prefix "dossier:Procedurestap")
  :properties `((:name :string ,(s-prefix "skos:prefLabel")))
  :resource-base (s-url "http://data.lblod.info/id/procedurestap/")
  :on-path "procedurestaps")

(define-resource aanvraag ()
  :class (s-prefix "omgeving:Aanvraag")
  :properties `((:name :string ,(s-prefix "dct:title")))
  :has-one `((dossier :via ,(s-prefix "omgeving:zaakhandeling")
                      :inverse t
                      :as "dossier")
             (recht :via ,(s-prefix "omgeving:inhoud")
                    :as "recht"))
  :resource-base (s-url "http://data.lblod.info/id/aanvragen/")
  :on-path "aanvraags")

(define-resource recht ()
  :class (s-prefix "omgeving:Recht")
  :properties `((:name :string ,(s-prefix "dct:title")))
  :has-one `((aanvraag :via ,(s-prefix "omgeving:inhoud")
                       :inverse t
                       :as "aanvraag"))
  :resource-base (s-url "http://data.lblod.info/id/aanvragen/")
  :on-path "rechts")


(define-resource persoon ()
  :class (s-prefix "person:Person")
  :properties `((:voornaam :string ,(s-prefix "foaf:firstName"))
                (:achternaam :string ,(s-prefix "foaf:familyName"))
                (:adres :string ,(s-prefix "schema:adres"))
                (:telefoon :string ,(s-prefix "schema:telephone"))
                (:mobiel :string ,(s-prefix "schema:mobile"))
                (:organisatie :string ,(s-prefix "ext:organisation")))
  :has-many `((activiteit :via ,(s-prefix "omgeving:betrokkene")
                          :inverse t
                          :as "activiteiten"))
  :resource-base (s-url "http://data.lblod.info/id/personen/")
  :features '(include-uri)
  :on-path "personen")

(define-resource activiteit ()
  :class (s-prefix "omgeving:Activiteit")
  :properties `((:name :string ,(s-prefix "dct:title"))
                (:date :date ,(s-prefix "ext:datum")))
  :has-one `((persoon :via ,(s-prefix "omgeving:betrokkene")
                   :as "organisator")
              (tijdsbestek :via ,(s-prefix "omgeving:Activiteit.tijdsbestek")
                   :as "tijdsbestek"))
  :resource-base (s-url "http://data.lblod.info/id/activiteiten/")
  :on-path "activiteiten")
