(define-resource dossier ()
  :class (s-prefix "dossier:Dossier")
  :properties `((:name :string ,(s-prefix "dct:title")))
  :has-one `((zaak :via ,(s-prefix "dossier:Dossier.isNeerslagVan")
                   :as "is-neerslag-van")
             (aanvraag :via ,(s-prefix "omgeving:zaakhandeling")
                       :as "aanvraag"))
  :resource-base (s-url "http://data.lblod.info/id/dossiers/")
  :on-path "dossiers")

(define-resource zaak ()
  :class (s-prefix "dossier:Zaak")
  :properties `((:name :string ,(s-prefix "dct:title"))
                (:opening-date :datetime ,(s-prefix "dossier:openingsdatum"))
                (:closing-date :datetime ,(s-prefix "dossier:sluitingsdatum")))
  ;; TODO: add status
  ;; TODO: link to municipality and organizer (via project)
  ;; :has-one `((bestuurseenheid :via ,(s-prefix "ext:organizedBy"))
  ;;                             :as "organizedBy")
  :has-one `((dossier :via ,(s-prefix "dossier:Dossier.isNeerslagVan")
                      :inverse t
                      :as "dossier")
              (procedurestap :via ,(s-prefix "dossier:doorloopt")
                             :as "procedurestap"))
  :resource-base (s-url "http://data.lblod.info/id/zaken/")
  :on-path "zaaks")

(define-resource procedurestap ()
  :class (s-prefix "dossier:Procedurestap")
  :properties `((:name :string ,(s-prefix "skos:prefLabel")))
  :resource-base (s-url "http://data.lblod.info/id/procedurestap/")
  :on-path "procedurestaps")

(define-resource aanvraag ()
  :class (s-prefix "omgeving:Aanvraag")
  :properties `((:name :string ,(s-prefix "dct:title")))
  :has-one `((dossier :via ,(s-prefix "omgeving:zaakhandeling")
                      :inverse t
                      :as dossier))
  :resource-base (s-url "http://data.lblod.info/id/aanvragen/")
  :on-path "aanvraags")
